import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

// Integration test against the actual local API/worker. Start npm run dev first.
const base=process.env.PTCG_BROWSER_URL||'http://127.0.0.1:5173';
const browser = await chromium.launch({headless:true});
try {
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}/#replays`);
  await page.getByText(/decks in the research pool/).waitFor();
  await page.getByRole('combobox',{name:/^Player 1/}).selectOption('crustle');
  await page.getByRole('combobox',{name:/^Player 2/}).selectOption('mega-lucario');
  await page.getByLabel('Seed',{exact:true}).fill('17');
  await page.getByRole('button',{name:'Run game',exact:true}).click();
  await page.getByRole('region',{name:'Pokémon card table',exact:true}).waitFor();
  const liveSlider=page.getByRole('slider',{name:'Replay position'});
  await page.getByRole('button',{name:'Pause playback',exact:true}).click();
  const pausedIndex=await liveSlider.inputValue();
  const arrived=Number(await liveSlider.getAttribute('max'));
  await expect.poll(async()=>Number(await liveSlider.getAttribute('max')),{timeout:30000}).toBeGreaterThan(arrived);
  assert.equal(await liveSlider.inputValue(),pausedIndex,'New simulator frames must not advance paused playback');
  await page.getByText(/won · rules-terminal/).waitFor({timeout:120000});
  const replayId = await page.getByRole('combobox',{name:/^Saved replay/}).inputValue();
  const replay = await (await page.request.get(`${base}/api/replays/${replayId}?playerId=0`)).json();
  assert.equal(replay.status,'finished');
  assert.equal(replay.schemaVersion,2);
  assert.equal(replay.seed,undefined);
  assert.ok(replay.frames.every(frame=>frame.observations===undefined&&frame.observation.players[1].hand.length===0));
  assert.ok(replay.frames.every(frame=>frame.observation.searchPosition===undefined),
    'Research reconstruction payloads must stay server-side');
  const index = replay.frames.findIndex(frame => frame.actor===0 && frame.action && frame.observation?.turn >= 2);
  assert.ok(index >= 0, 'Expected a real pre-decision position');
  await page.getByRole('combobox',{name:/^Perspective/}).selectOption('0');
  if(await page.getByRole('button',{name:'Pause playback',exact:true}).count())await page.getByRole('button',{name:'Pause playback',exact:true}).click();
  const slider=page.getByRole('slider',{name:'Replay position'});
  await slider.focus(); await slider.press('Home');
  for(let i=0;i<index;i++) await slider.press('ArrowRight');
  assert.equal(await slider.inputValue(),String(index));
  const saveResponse=page.waitForResponse(response => response.url().endsWith('/api/positions') && response.request().method()==='POST');
  await page.getByRole('button',{name:'Save position',exact:true}).click();
  const saved=await (await saveResponse).json();
  await page.getByRole('combobox',{name:/^Saved position/}).selectOption(saved.id);
  await page.getByRole('button',{name:'Open source replay'}).waitFor();
  assert.equal(await page.getByRole('combobox',{name:/^Perspective/}).isDisabled(),true);
  const position=await (await page.request.get(`${base}/api/positions/${saved.id}`)).json();
  assert.equal(position.frames,undefined);
  assert.equal(position.observation.players[1-position.playerId].hand.length,0);
  const analysis=await (await page.request.post(`${base}/api/analyze`,{data:{positionId:saved.id,budgetMs:500}})).json();
  assert.ok(analysis.evaluation);
  assert.ok(['complete','unavailable'].includes(analysis.search.status));
  if(analysis.search.status==='unavailable') assert.ok(analysis.warnings.some(w=>/unavailable|unsupported/i.test(w)),
    'Unsupported search must explain its coverage limit');
  if(!analysis.evaluation.calibrated) assert.equal(analysis.evaluation.winProbability,null);
  await page.waitForTimeout(800);
  const meter=page.getByRole('meter');
  await meter.waitFor();
  assert.ok(Number(await meter.getAttribute('aria-valuenow')) >= -6);
  assert.ok(Number(await meter.getAttribute('aria-valuenow')) <= 6);
  await mkdir('artifacts/browser',{recursive:true});
  await page.screenshot({path:'artifacts/browser/desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'artifacts/browser/mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Open source replay'}).click();
  await page.getByRole('combobox',{name:/^Perspective/}).selectOption('1');
  const other=await (await page.request.get(`${base}/api/replays/${replayId}?playerId=1`)).json();
  assert.ok(other.frames.every(f=>f.observation.playerId===1&&f.observation.players[0].hand.length===0&&f.observations===undefined));
  await expect(page.locator('.our-side .table-counts strong')).toHaveText('Player 2');
  await page.reload();
  await expect(page.getByRole('combobox',{name:/^Perspective/})).toHaveValue('1');
  await expect(page.getByRole('combobox',{name:/^Saved replay/})).toHaveValue(replayId);
  await expect(page.locator('.our-side .table-counts strong')).toHaveText('Player 2');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,replayId,positionId:saved.id,frames:replay.frames.length,evaluation:analysis.evaluation.status,search:analysis.search,pageErrors:errors,mobileOverflow:false,livePlayback:true,presentationPauseIndependent:true,perspectiveProjection:true,reloadRestoresSource:true}));
} finally {await browser.close();}
