// Generated by scripts/create-catalog.py. Explicit imports prevent loading every set.
import { Dreepy as C0 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/dreepy';
import { Drakloak as C1 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/drakloak';
import { Dragapultex as C2 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/dragapult-ex';
import { TealMaskOgerponex as C3 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/teal-mask-ogerpon-ex';
import { Munkidori as C4 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/munkidori';
import { Hawlucha as C5 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/hawlucha';
import { Carmine as C6 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/carmine';
import { RagingBoltex as C7 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/raging-bolt-ex';
import { BuddyBuddyPoffin as C8 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/buddy-buddy-poffin';
import { HandTrimmer as C9 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/hand-trimmer';
import { MarniesImpidimp as C10 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/marnies-impidimp';
import { MarniesMorgrem as C11 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/marnies-morgrem';
import { MarniesGrimmsnarlex as C12 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/marnies-grimmsnarl-ex';
import { Dwebble as C13 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/dwebble';
import { Crustle as C14 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/crustle';
import { Shaymin as C15 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/shaymin';
import { NightlyStretcher as C16 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-shrouded-fable/nightly-stretcher';
import { Fezandipitiex as C17 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-shrouded-fable/fezandipiti-ex';
import { Crispin as C18 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-stellar-crown/crispin';
import { GravityGemstone as C19 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-stellar-crown/gravity-gemstone';
import { Riolu as C20 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/riolu';
import { MegaLucarioex as C21 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/mega-lucario-ex';
import { LilliesDetermination as C22 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/lillies-determination';
import { FightingGong as C23 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/fighting-gong';
import { MegaSignal as C24 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/mega-signal';
import { WallysCompassion as C25 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/wallys-compassion';
import { BossOrders as C26 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-paldea-evolved/boss-orders';
import { RareCandy as C27 } from '../../../vendor/twinleaf/ptcg-server/src/sets/03-ex-ruby-and-sapphire/set-ex-holon-phantoms/rare-candy';
import { Switch as C28 } from '../../../vendor/twinleaf/ptcg-server/src/sets/set-base-set/switch';
import { UltraBall as C29 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet/ultra-ball';
import { EnergySwitch as C30 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet/energy-switch';
import { GrassEnergy as C31 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/grass-energy';
import { FireEnergy as C32 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/fire-energy';
import { LightningEnergy as C33 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/lightning-energy';
import { PsychicEnergy as C34 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/psychic-energy';
import { FightingEnergy as C35 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/fighting-energy';
import { DarknessEnergy as C36 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/darkness-energy';
import { CardManager } from '../../../vendor/twinleaf/ptcg-server/src/game/cards/card-manager';
import { Card } from '../../../vendor/twinleaf/ptcg-server/src/game/store/card/card';
import { SuperType, Stage, EnergyType } from '../../../vendor/twinleaf/ptcg-server/src/game/store/card/card-types';
import dragapult from '../../../decks/dragapult.json';
import ragingBolt from '../../../decks/raging-bolt.json';
import grimmsnarl from '../../../decks/grimmsnarl.json';
import megaLucario from '../../../decks/mega-lucario.json';
import crustle from '../../../decks/crustle.json';
import format from '../../../formats/standard-2026-09-17.json';
export const CARD_FACTORIES: Record<string, () => Card> = {
  "TWM-128": () => Object.assign(new C0(), {}),
  "TWM-129": () => Object.assign(new C1(), {}),
  "TWM-130": () => Object.assign(new C2(), {}),
  "TWM-25": () => Object.assign(new C3(), {}),
  "TWM-95": () => Object.assign(new C4(), {}),
  "TWM-107": () => Object.assign(new C5(), {}),
  "TWM-145": () => Object.assign(new C6(), {}),
  "TEF-123": () => Object.assign(new C7(), {}),
  "TEF-144": () => Object.assign(new C8(), {}),
  "TEF-150": () => Object.assign(new C9(), {}),
  "DRI-134": () => Object.assign(new C10(), {}),
  "DRI-135": () => Object.assign(new C11(), {}),
  "DRI-136": () => Object.assign(new C12(), {}),
  "DRI-11": () => Object.assign(new C13(), {}),
  "DRI-12": () => Object.assign(new C14(), {}),
  "DRI-10": () => Object.assign(new C15(), {}),
  "SFA-61": () => Object.assign(new C16(), {}),
  "SFA-38": () => Object.assign(new C17(), {}),
  "SCR-133": () => Object.assign(new C18(), {}),
  "SCR-137": () => Object.assign(new C19(), {}),
  "MEG-76": () => Object.assign(new C20(), {}),
  "MEG-77": () => Object.assign(new C21(), {}),
  "MEG-119": () => Object.assign(new C22(), {}),
  "MEG-116": () => Object.assign(new C23(), {}),
  "MEG-121": () => Object.assign(new C24(), {}),
  "MEG-132": () => Object.assign(new C25(), {}),
  "MEG-114": () => Object.assign(new C26(), {"set": "MEG", "setNumber": "114", "regulationMark": "I", "fullName": "Boss's Orders MEG"}),
  "MEG-125": () => Object.assign(new C27(), {"set": "MEG", "setNumber": "125", "regulationMark": "I", "fullName": "Rare Candy MEG"}),
  "MEG-130": () => Object.assign(new C28(), {"set": "MEG", "setNumber": "130", "regulationMark": "I", "fullName": "Switch MEG"}),
  "MEG-131": () => Object.assign(new C29(), {"set": "MEG", "setNumber": "131", "regulationMark": "I", "fullName": "Ultra Ball MEG"}),
  "MEG-115": () => Object.assign(new C30(), {"set": "MEG", "setNumber": "115", "regulationMark": "I", "fullName": "Energy Switch MEG"}),
  "SVE-1": () => Object.assign(new C31(), {}),
  "SVE-2": () => Object.assign(new C32(), {}),
  "SVE-4": () => Object.assign(new C33(), {}),
  "SVE-5": () => Object.assign(new C34(), {}),
  "SVE-6": () => Object.assign(new C35(), {}),
  "SVE-7": () => Object.assign(new C36(), {}),
};
export const CARD_METADATA = {
  "TWM-128": {
    "cardId": "TWM-128",
    "name": "Dreepy",
    "engineName": "Dreepy TWM",
    "regulationMark": "H"
  },
  "TWM-129": {
    "cardId": "TWM-129",
    "name": "Drakloak",
    "engineName": "Drakloak TWM",
    "regulationMark": "H"
  },
  "TWM-130": {
    "cardId": "TWM-130",
    "name": "Dragapult ex",
    "engineName": "Dragapult ex TWM",
    "regulationMark": "H"
  },
  "TWM-25": {
    "cardId": "TWM-25",
    "name": "Teal Mask Ogerpon ex",
    "engineName": "Teal Mask Ogerpon ex TWM",
    "regulationMark": "H"
  },
  "TWM-95": {
    "cardId": "TWM-95",
    "name": "Munkidori",
    "engineName": "Munkidori TWM",
    "regulationMark": "H"
  },
  "TWM-107": {
    "cardId": "TWM-107",
    "name": "Hawlucha",
    "engineName": "Hawlucha TWM",
    "regulationMark": "H"
  },
  "TWM-145": {
    "cardId": "TWM-145",
    "name": "Carmine",
    "engineName": "Carmine TWM",
    "regulationMark": "H"
  },
  "TEF-123": {
    "cardId": "TEF-123",
    "name": "Raging Bolt ex",
    "engineName": "Raging Bolt ex TEF",
    "regulationMark": "H"
  },
  "TEF-144": {
    "cardId": "TEF-144",
    "name": "Buddy-Buddy Poffin",
    "engineName": "Buddy-Buddy Poffin TEF",
    "regulationMark": "H"
  },
  "TEF-150": {
    "cardId": "TEF-150",
    "name": "Hand Trimmer",
    "engineName": "Hand Trimmer TEF",
    "regulationMark": "H"
  },
  "DRI-134": {
    "cardId": "DRI-134",
    "name": "Marnie's Impidimp",
    "engineName": "Marnie's Impidimp DRI",
    "regulationMark": "I"
  },
  "DRI-135": {
    "cardId": "DRI-135",
    "name": "Marnie's Morgrem",
    "engineName": "Marnie's Morgrem DRI",
    "regulationMark": "I"
  },
  "DRI-136": {
    "cardId": "DRI-136",
    "name": "Marnie's Grimmsnarl ex",
    "engineName": "Marnie's Grimmsnarl ex DRI",
    "regulationMark": "I"
  },
  "DRI-11": {
    "cardId": "DRI-11",
    "name": "Dwebble",
    "engineName": "Dwebble DRI",
    "regulationMark": "I"
  },
  "DRI-12": {
    "cardId": "DRI-12",
    "name": "Crustle",
    "engineName": "Crustle DRI",
    "regulationMark": "I"
  },
  "DRI-10": {
    "cardId": "DRI-10",
    "name": "Shaymin",
    "engineName": "Shaymin DRI",
    "regulationMark": "I"
  },
  "SFA-61": {
    "cardId": "SFA-61",
    "name": "Night Stretcher",
    "engineName": "Night Stretcher SFA",
    "regulationMark": "H"
  },
  "SFA-38": {
    "cardId": "SFA-38",
    "name": "Fezandipiti ex",
    "engineName": "Fezandipiti ex SFA",
    "regulationMark": "H"
  },
  "SCR-133": {
    "cardId": "SCR-133",
    "name": "Crispin",
    "engineName": "Crispin SCR",
    "regulationMark": "H"
  },
  "SCR-137": {
    "cardId": "SCR-137",
    "name": "Gravity Gemstone",
    "engineName": "Gravity Gemstone SCR",
    "regulationMark": "H"
  },
  "MEG-76": {
    "cardId": "MEG-76",
    "name": "Riolu",
    "engineName": "Riolu M1L",
    "regulationMark": "I"
  },
  "MEG-77": {
    "cardId": "MEG-77",
    "name": "Mega Lucario ex",
    "engineName": "Mega Lucario ex M1L",
    "regulationMark": "I"
  },
  "MEG-119": {
    "cardId": "MEG-119",
    "name": "Lillie's Determination",
    "engineName": "Lillie's Determination M1L",
    "regulationMark": "I"
  },
  "MEG-116": {
    "cardId": "MEG-116",
    "name": "Fighting Gong",
    "engineName": "Fighting Gong M1L",
    "regulationMark": "I"
  },
  "MEG-121": {
    "cardId": "MEG-121",
    "name": "Mega Signal",
    "engineName": "Mega Signal M1S",
    "regulationMark": "I"
  },
  "MEG-132": {
    "cardId": "MEG-132",
    "name": "Wally's Compassion",
    "engineName": "Wally's Compassion M1S",
    "regulationMark": "I"
  },
  "MEG-114": {
    "cardId": "MEG-114",
    "name": "Boss's Orders",
    "engineName": "Boss's Orders MEG",
    "regulationMark": "I"
  },
  "MEG-125": {
    "cardId": "MEG-125",
    "name": "Rare Candy",
    "engineName": "Rare Candy MEG",
    "regulationMark": "I"
  },
  "MEG-130": {
    "cardId": "MEG-130",
    "name": "Switch",
    "engineName": "Switch MEG",
    "regulationMark": "I"
  },
  "MEG-131": {
    "cardId": "MEG-131",
    "name": "Ultra Ball",
    "engineName": "Ultra Ball MEG",
    "regulationMark": "I"
  },
  "MEG-115": {
    "cardId": "MEG-115",
    "name": "Energy Switch",
    "engineName": "Energy Switch MEG",
    "regulationMark": "I"
  },
  "SVE-1": {
    "cardId": "SVE-1",
    "name": "Grass Energy",
    "engineName": "Grass Energy SVE",
    "regulationMark": "ENERGY"
  },
  "SVE-2": {
    "cardId": "SVE-2",
    "name": "Fire Energy",
    "engineName": "Fire Energy SVE",
    "regulationMark": "ENERGY"
  },
  "SVE-4": {
    "cardId": "SVE-4",
    "name": "Lightning Energy",
    "engineName": "Lightning Energy SVE",
    "regulationMark": "ENERGY"
  },
  "SVE-5": {
    "cardId": "SVE-5",
    "name": "Psychic Energy",
    "engineName": "Psychic Energy SVE",
    "regulationMark": "ENERGY"
  },
  "SVE-6": {
    "cardId": "SVE-6",
    "name": "Fighting Energy",
    "engineName": "Fighting Energy SVE",
    "regulationMark": "ENERGY"
  },
  "SVE-7": {
    "cardId": "SVE-7",
    "name": "Darkness Energy",
    "engineName": "Darkness Energy SVE",
    "regulationMark": "ENERGY"
  }
} as const;
export type DeckManifest = typeof dragapult;
const manifests = [dragapult, ragingBolt, grimmsnarl, megaLucario, crustle];
let registered = false;
export function registerCards(): void {
  if (registered) return;
  const manager = CardManager.getInstance();
  for (const factory of Object.values(CARD_FACTORIES)) manager.defineCard(factory());
  registered = true;
}
export function validateDeck(deck: DeckManifest): string[] {
  const errors: string[] = [];
  if(deck.formatDate!==format.date) errors.push('Unsupported format freeze: '+deck.formatDate);
  if (deck.cards.reduce((n,c)=>n+c.count,0)!==60) errors.push('Deck must contain exactly 60 cards.');
  const counts = new Map<string,number>(); let basic = false;
  for (const entry of deck.cards) {
    if (!Number.isInteger(entry.count) || entry.count < 1) errors.push('Invalid count: '+entry.cardId);
    const factory = CARD_FACTORIES[entry.cardId];
    if (!factory) { errors.push('Unsupported card: '+entry.cardId); continue; }
    const card = factory();
    const set = entry.cardId.split('-')[0] as keyof typeof format.sets;
    if(!format.sets[set] || format.sets[set].released>format.date) errors.push('Unreleased or unverified set: '+set);
    if (card.fullName !== entry.engineName) errors.push('Engine mapping mismatch: '+entry.cardId);
    const energy = card.superType===SuperType.ENERGY && card.energyType===EnergyType.BASIC;
    if (!energy && !['H','I','J'].includes(card.regulationMark)) errors.push('Rotated card: '+entry.cardId);
    if (!energy) counts.set(card.name,(counts.get(card.name)??0)+entry.count);
    if (card.superType===SuperType.POKEMON && (card as any).stage===Stage.BASIC) basic=true;
  }
  for (const [name,count] of counts) if(count>4) errors.push('More than four copies: '+name);
  if(!basic) errors.push('Deck needs a Basic Pokemon.');
  return errors;
}
export function getDecks() {
  return manifests.map(d=>({...d,cardCount:d.cards.reduce((n,c)=>n+c.count,0),support:{playable:validateDeck(d).length===0,errors:validateDeck(d)}}));
}
export function getDeck(id: string): DeckManifest {
  const deck = manifests.find(d=>d.id===id);
  if(!deck) throw new Error('Unknown deck: '+id);
  const errors = validateDeck(deck);
  if(errors.length) throw new Error(errors.join(' '));
  return deck;
}
export function deckNames(id: string): string[] {
  return getDeck(id).cards.flatMap(c=>Array(c.count).fill(c.engineName));
}
export function instantiateDeck(id: string): Card[] {
  registerCards();
  return getDeck(id).cards.flatMap(c=>Array.from({length:c.count},()=>CARD_FACTORIES[c.cardId]()));
}
export function printedId(card: Card): string {
  return Object.entries(CARD_METADATA).find(([,m])=>m.engineName===card.fullName)?.[0] ?? `${card.set}-${card.setNumber}`;
}
