// Generated by scripts/create-catalog.py; do not edit.
import { Dreepy as C0 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/dreepy';
import { Drakloak as C1 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/drakloak';
import { Dragapultex as C2 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/dragapult-ex';
import { TealMaskOgerponex as C3 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/teal-mask-ogerpon-ex';
import { Munkidori as C4 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/munkidori';
import { Hawlucha as C5 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/hawlucha';
import { Carmine as C6 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/carmine';
import { RagingBoltex as C7 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/raging-bolt-ex';
import { BuddyBuddyPoffin as C8 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/buddy-buddy-poffin';
import { HandTrimmer as C9 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/hand-trimmer';
import { MarniesImpidimp as C10 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/marnies-impidimp';
import { MarniesMorgrem as C11 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/marnies-morgrem';
import { MarniesGrimmsnarlex as C12 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/marnies-grimmsnarl-ex';
import { Dwebble as C13 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/dwebble';
import { Crustle as C14 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/crustle';
import { Shaymin as C15 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/shaymin';
import { NightlyStretcher as C16 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-shrouded-fable/nightly-stretcher';
import { Fezandipitiex as C17 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-shrouded-fable/fezandipiti-ex';
import { Crispin as C18 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-stellar-crown/crispin';
import { GravityGemstone as C19 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-stellar-crown/gravity-gemstone';
import { Riolu as C20 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/riolu';
import { MegaLucarioex as C21 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/mega-lucario-ex';
import { LilliesDetermination as C22 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/lillies-determination';
import { FightingGong as C23 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/fighting-gong';
import { MegaSignal as C24 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/mega-signal';
import { WallysCompassion as C25 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/wallys-compassion';
import { BossOrders as C26 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-paldea-evolved/boss-orders';
import { RareCandy as C27 } from '../../../vendor/twinleaf/ptcg-server/src/sets/03-ex-ruby-and-sapphire/set-ex-holon-phantoms/rare-candy';
import { Switch as C28 } from '../../../vendor/twinleaf/ptcg-server/src/sets/set-base-set/switch';
import { UltraBall as C29 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet/ultra-ball';
import { EnergySwitch as C30 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet/energy-switch';
import { GrassEnergy as C31 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/grass-energy';
import { FireEnergy as C32 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/fire-energy';
import { LightningEnergy as C33 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/lightning-energy';
import { PsychicEnergy as C34 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/psychic-energy';
import { FightingEnergy as C35 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/fighting-energy';
import { DarknessEnergy as C36 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/darkness-energy';
import { Meowthex as C37 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-perfect-order/meowth-ex';
import { RosasEncouragement as C38 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-perfect-order/rosas-encouragement';
import { PokePad as C39 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-ascended-heroes/poke-pad';
import { Judge as C40 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet/judge';
import { CrushingHammer as C41 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet/crushing-hammer';
import { MegaKangaskhanex as C42 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/mega-kangaskhan-ex';
import { Solrock as C43 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/solrock';
import { Lunatone as C44 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/lunatone';
import { Makuhita as C45 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/makuhita';
import { Hariyama as C46 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/hariyama';
import { Yveltal as C47 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/yveltal';
import { PowerProtein as C48 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/power-protein';
import { DangerousRuins as C49 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-mega-evolution/risky-ruins';
import { Budew as C50 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-prismatic-evolution/budew';
import { Snorunt as C51 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-ascended-heroes/snorunt';
import { Fezandipitiex as C52 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-shrouded-fable/fezandipiti-ex';
import { AirBalloon as C53 } from '../../../vendor/twinleaf/ptcg-server/src/sets/09-sword-and-shield/set-sword-and-shield/air-balloon';
import { NightlyStretcher as C54 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-shrouded-fable/nightly-stretcher';
import { Gwynn as C55 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-pitch-black/gwynn';
import { Froslass as C56 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/froslass';
import { BloodmoonUrsalunaex as C57 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/bloodmoon-ursaluna-ex';
import { WellspringMaskOgerponex as C58 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/wellspring-mask-ogerpon-ex';
import { SecretBox as C59 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/secret-box';
import { UnfairStamp as C60 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/unfair-stamp';
import { HandyFan as C61 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/handy-fan';
import { EnhancedHammer as C62 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/enhanced-hammer';
import { TeamRocketsPetrel as C63 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/team-rockets-petrel';
import { SpikemuthGym as C64 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/spikemuth-gym';
import { Latiasex as C65 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-surging-sparks/latias-ex';
import { ChienPao as C66 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-surging-sparks/chien-pao';
import { GravityMountain as C67 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-surging-sparks/gravity-mountain';
import { Cyrano as C68 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-surging-sparks/cyrano';
import { LilliesClefairyex as C69 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-journey-together/lillies-clefairy-ex';
import { Dunsparce as C70 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-journey-together/dunsparce';
import { SpikyEnergy as C71 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-journey-together/spiky-energy';
import { IronLeavesex as C72 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/iron-leaves-ex';
import { Dudunsparce as C73 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/dudunsparce';
import { CiphermaniacsCodebreaking as C74 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/cryptomaniacs-deciphering';
import { MistEnergy as C75 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/mist-energy';
import { AreaZeroUnderdepths as C76 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-stellar-crown/area-zero-underdepths';
import { GlassTrumpet as C77 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-stellar-crown/glass-trumpet';
import { XerosicsScheme as C78 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-shrouded-fable/xerosics-scheme';
import { JumboIce as C79 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-phantasmal-flames/jumbo-ice';
import { SpecialRedCard as C80 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-chaos-rising/special-red-card';
import { PrismTower as C81 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-chaos-rising/prism-tower';
import { TeamRocketsFactory as C82 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-destined-rivals/team-rockets-factory';
import { Eri as C83 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/eri';
import { HerosCape as C84 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-temporal-forces/heros-cape';
import { Hilda as C85 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-black-bolt-white-flare/hilda';
import { LumioiseCity as C86 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-perfect-order/lumioise-city';
import { GrowGrassEnergy as C87 } from '../../../vendor/twinleaf/ptcg-server/src/sets/11-mega-evolution/set-perfect-order/grow-grass-energy';
import { GrassEnergy as C88 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/grass-energy';
import { FireEnergy as C89 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/fire-energy';
import { WaterEnergy as C90 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/water-energy';
import { LightningEnergy as C91 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/lightning-energy';
import { PsychicEnergy as C92 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/psychic-energy';
import { FightingEnergy as C93 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/fighting-energy';
import { DarknessEnergy as C94 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet-energy/darkness-energy';
import { FestivalGrounds as C95 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-twilight-masquerade/festival-plaza';
import { Pokegear30 as C96 } from '../../../vendor/twinleaf/ptcg-server/src/sets/10-scarlet-and-violet/set-scarlet-and-violet/pokegear-30';
import { PokemonCenterLady as C97 } from '../../../vendor/twinleaf/ptcg-server/src/sets/07-x-and-y/set-flashfire/pokemon-center-lady';
import D0 from '../../../decks/crustle-heldout.json';
import D1 from '../../../decks/crustle-training.json';
import D2 from '../../../decks/crustle.json';
import D3 from '../../../decks/dragapult-heldout.json';
import D4 from '../../../decks/dragapult-training.json';
import D5 from '../../../decks/dragapult.json';
import D6 from '../../../decks/grimmsnarl-heldout.json';
import D7 from '../../../decks/grimmsnarl-training.json';
import D8 from '../../../decks/grimmsnarl.json';
import D9 from '../../../decks/historical/crustle.json';
import D10 from '../../../decks/historical/dragapult.json';
import D11 from '../../../decks/historical/grimmsnarl.json';
import D12 from '../../../decks/historical/mega-lucario.json';
import D13 from '../../../decks/historical/raging-bolt.json';
import D14 from '../../../decks/mega-lucario-heldout.json';
import D15 from '../../../decks/mega-lucario-training.json';
import D16 from '../../../decks/mega-lucario.json';
import D17 from '../../../decks/raging-bolt-heldout.json';
import D18 from '../../../decks/raging-bolt-training.json';
import D19 from '../../../decks/raging-bolt.json';
import { Card } from '../../../vendor/twinleaf/ptcg-server/src/game/store/card/card';
export const CARD_FACTORIES: Record<string, () => Card> = {
  "TWM-128": () => Object.assign(new C0(), {"set": "TWM", "setNumber": "128", "fullName": "Dreepy TWM-128", "regulationMark": "H"}),
  "TWM-129": () => Object.assign(new C1(), {"set": "TWM", "setNumber": "129", "fullName": "Drakloak TWM-129", "regulationMark": "H"}),
  "TWM-130": () => Object.assign(new C2(), {"set": "TWM", "setNumber": "130", "fullName": "Dragapult ex TWM-130", "regulationMark": "H"}),
  "TWM-25": () => Object.assign(new C3(), {"set": "TWM", "setNumber": "25", "fullName": "Teal Mask Ogerpon ex TWM-25", "regulationMark": "H"}),
  "TWM-95": () => Object.assign(new C4(), {"set": "TWM", "setNumber": "95", "fullName": "Munkidori TWM-95", "regulationMark": "H"}),
  "TWM-107": () => Object.assign(new C5(), {"set": "TWM", "setNumber": "107", "fullName": "Hawlucha TWM-107", "regulationMark": "H"}),
  "TWM-145": () => Object.assign(new C6(), {"set": "TWM", "setNumber": "145", "fullName": "Carmine TWM-145", "regulationMark": "H"}),
  "TEF-123": () => Object.assign(new C7(), {"set": "TEF", "setNumber": "123", "fullName": "Raging Bolt ex TEF-123", "regulationMark": "H"}),
  "TEF-144": () => Object.assign(new C8(), {"set": "TEF", "setNumber": "144", "fullName": "Buddy-Buddy Poffin TEF-144", "regulationMark": "H"}),
  "TEF-150": () => Object.assign(new C9(), {"set": "TEF", "setNumber": "150", "fullName": "Hand Trimmer TEF-150", "regulationMark": "H"}),
  "DRI-134": () => Object.assign(new C10(), {"set": "DRI", "setNumber": "134", "fullName": "Marnie's Impidimp DRI-134", "regulationMark": "I"}),
  "DRI-135": () => Object.assign(new C11(), {"set": "DRI", "setNumber": "135", "fullName": "Marnie's Morgrem DRI-135", "regulationMark": "I"}),
  "DRI-136": () => Object.assign(new C12(), {"set": "DRI", "setNumber": "136", "fullName": "Marnie's Grimmsnarl ex DRI-136", "regulationMark": "I"}),
  "DRI-11": () => Object.assign(new C13(), {"set": "DRI", "setNumber": "11", "fullName": "Dwebble DRI-11", "regulationMark": "I"}),
  "DRI-12": () => Object.assign(new C14(), {"set": "DRI", "setNumber": "12", "fullName": "Crustle DRI-12", "regulationMark": "I"}),
  "DRI-10": () => Object.assign(new C15(), {"set": "DRI", "setNumber": "10", "fullName": "Shaymin DRI-10", "regulationMark": "I"}),
  "SFA-61": () => Object.assign(new C16(), {"set": "SFA", "setNumber": "61", "fullName": "Night Stretcher SFA-61", "regulationMark": "H"}),
  "SFA-38": () => Object.assign(new C17(), {"set": "SFA", "setNumber": "38", "fullName": "Fezandipiti ex SFA-38", "regulationMark": "H"}),
  "SCR-133": () => Object.assign(new C18(), {"set": "SCR", "setNumber": "133", "fullName": "Crispin SCR-133", "regulationMark": "H"}),
  "SCR-137": () => Object.assign(new C19(), {"set": "SCR", "setNumber": "137", "fullName": "Gravity Gemstone SCR-137", "regulationMark": "H"}),
  "MEG-76": () => Object.assign(new C20(), {"set": "MEG", "setNumber": "76", "fullName": "Riolu MEG-76", "regulationMark": "I"}),
  "MEG-77": () => Object.assign(new C21(), {"set": "MEG", "setNumber": "77", "fullName": "Mega Lucario ex MEG-77", "regulationMark": "I"}),
  "MEG-119": () => Object.assign(new C22(), {"set": "MEG", "setNumber": "119", "fullName": "Lillie's Determination MEG-119", "regulationMark": "I"}),
  "MEG-116": () => Object.assign(new C23(), {"set": "MEG", "setNumber": "116", "fullName": "Fighting Gong MEG-116", "regulationMark": "I"}),
  "MEG-121": () => Object.assign(new C24(), {"set": "MEG", "setNumber": "121", "fullName": "Mega Signal MEG-121", "regulationMark": "I"}),
  "MEG-132": () => Object.assign(new C25(), {"set": "MEG", "setNumber": "132", "fullName": "Wally's Compassion MEG-132", "regulationMark": "I"}),
  "MEG-114": () => Object.assign(new C26(), {"set": "MEG", "setNumber": "114", "fullName": "Boss's Orders MEG-114", "regulationMark": "I"}),
  "MEG-125": () => Object.assign(new C27(), {"set": "MEG", "setNumber": "125", "fullName": "Rare Candy MEG-125", "regulationMark": "I"}),
  "MEG-130": () => Object.assign(new C28(), {"set": "MEG", "setNumber": "130", "fullName": "Switch MEG-130", "regulationMark": "I"}),
  "MEG-131": () => Object.assign(new C29(), {"set": "MEG", "setNumber": "131", "fullName": "Ultra Ball MEG-131", "regulationMark": "I"}),
  "MEG-115": () => Object.assign(new C30(), {"set": "MEG", "setNumber": "115", "fullName": "Energy Switch MEG-115", "regulationMark": "I"}),
  "SVE-1": () => Object.assign(new C31(), {"set": "SVE", "setNumber": "1", "fullName": "Grass Energy SVE-1", "regulationMark": "ENERGY"}),
  "SVE-2": () => Object.assign(new C32(), {"set": "SVE", "setNumber": "2", "fullName": "Fire Energy SVE-2", "regulationMark": "ENERGY"}),
  "SVE-4": () => Object.assign(new C33(), {"set": "SVE", "setNumber": "4", "fullName": "Lightning Energy SVE-4", "regulationMark": "ENERGY"}),
  "SVE-5": () => Object.assign(new C34(), {"set": "SVE", "setNumber": "5", "fullName": "Psychic Energy SVE-5", "regulationMark": "ENERGY"}),
  "SVE-6": () => Object.assign(new C35(), {"set": "SVE", "setNumber": "6", "fullName": "Fighting Energy SVE-6", "regulationMark": "ENERGY"}),
  "SVE-7": () => Object.assign(new C36(), {"set": "SVE", "setNumber": "7", "fullName": "Darkness Energy SVE-7", "regulationMark": "ENERGY"}),
  "POR-62": () => Object.assign(new C37(), {"set": "POR", "setNumber": "62", "fullName": "Meowth ex POR-62", "regulationMark": "J"}),
  "POR-84": () => Object.assign(new C38(), {"set": "POR", "setNumber": "84", "fullName": "Rosa's Encouragement POR-84", "regulationMark": "J"}),
  "POR-81": () => Object.assign(new C39(), {"set": "POR", "setNumber": "81", "fullName": "Pok\u00e9 Pad POR-81", "regulationMark": "J"}),
  "POR-76": () => Object.assign(new C40(), {"set": "POR", "setNumber": "76", "fullName": "Judge POR-76", "regulationMark": "J"}),
  "POR-71": () => Object.assign(new C41(), {"set": "POR", "setNumber": "71", "fullName": "Crushing Hammer POR-71", "regulationMark": "J"}),
  "MEG-104": () => Object.assign(new C42(), {"set": "MEG", "setNumber": "104", "fullName": "Mega Kangaskhan ex MEG-104", "regulationMark": "I"}),
  "MEG-75": () => Object.assign(new C43(), {"set": "MEG", "setNumber": "75", "fullName": "Solrock MEG-75", "regulationMark": "I"}),
  "MEG-74": () => Object.assign(new C44(), {"set": "MEG", "setNumber": "74", "fullName": "Lunatone MEG-74", "regulationMark": "I"}),
  "MEG-72": () => Object.assign(new C45(), {"set": "MEG", "setNumber": "72", "fullName": "Makuhita MEG-72", "regulationMark": "I"}),
  "MEG-73": () => Object.assign(new C46(), {"set": "MEG", "setNumber": "73", "fullName": "Hariyama MEG-73", "regulationMark": "I"}),
  "MEG-88": () => Object.assign(new C47(), {"set": "MEG", "setNumber": "88", "fullName": "Yveltal MEG-88", "regulationMark": "I"}),
  "MEG-124": () => Object.assign(new C48(), {"set": "MEG", "setNumber": "124", "fullName": "Premium Power Pro MEG-124", "regulationMark": "I"}),
  "MEG-127": () => Object.assign(new C49(), {"set": "MEG", "setNumber": "127", "fullName": "Risky Ruins MEG-127", "regulationMark": "I"}),
  "ASC-16": () => Object.assign(new C50(), {"set": "ASC", "setNumber": "16", "fullName": "Budew ASC-16", "regulationMark": "H"}),
  "ASC-46": () => Object.assign(new C51(), {"set": "ASC", "setNumber": "46", "fullName": "Snorunt ASC-46", "regulationMark": "I"}),
  "ASC-142": () => Object.assign(new C52(), {"set": "ASC", "setNumber": "142", "fullName": "Fezandipiti ex ASC-142", "regulationMark": "H"}),
  "ASC-181": () => Object.assign(new C53(), {"set": "ASC", "setNumber": "181", "fullName": "Air Balloon ASC-181", "regulationMark": "I"}),
  "ASC-196": () => Object.assign(new C54(), {"set": "ASC", "setNumber": "196", "fullName": "Night Stretcher ASC-196", "regulationMark": "H"}),
  "PBL-78": () => Object.assign(new C55(), {"set": "PBL", "setNumber": "78", "fullName": "Gwynn PBL-78", "regulationMark": "J"}),
  "TWM-53": () => Object.assign(new C56(), {"set": "TWM", "setNumber": "53", "fullName": "Froslass TWM-53", "regulationMark": "H"}),
  "TWM-141": () => Object.assign(new C57(), {"set": "TWM", "setNumber": "141", "fullName": "Bloodmoon Ursaluna ex TWM-141", "regulationMark": "H"}),
  "TWM-64": () => Object.assign(new C58(), {"set": "TWM", "setNumber": "64", "fullName": "Wellspring Mask Ogerpon ex TWM-64", "regulationMark": "H"}),
  "TWM-163": () => Object.assign(new C59(), {"set": "TWM", "setNumber": "163", "fullName": "Secret Box TWM-163", "regulationMark": "H"}),
  "TWM-165": () => Object.assign(new C60(), {"set": "TWM", "setNumber": "165", "fullName": "Unfair Stamp TWM-165", "regulationMark": "H"}),
  "TWM-150": () => Object.assign(new C61(), {"set": "TWM", "setNumber": "150", "fullName": "Handheld Fan TWM-150", "regulationMark": "H"}),
  "TWM-148": () => Object.assign(new C62(), {"set": "TWM", "setNumber": "148", "fullName": "Enhanced Hammer TWM-148", "regulationMark": "H"}),
  "DRI-176": () => Object.assign(new C63(), {"set": "DRI", "setNumber": "176", "fullName": "Team Rocket's Petrel DRI-176", "regulationMark": "I"}),
  "DRI-169": () => Object.assign(new C64(), {"set": "DRI", "setNumber": "169", "fullName": "Spikemuth Gym DRI-169", "regulationMark": "I"}),
  "SSP-76": () => Object.assign(new C65(), {"set": "SSP", "setNumber": "76", "fullName": "Latias ex SSP-76", "regulationMark": "H"}),
  "SSP-56": () => Object.assign(new C66(), {"set": "SSP", "setNumber": "56", "fullName": "Chien-Pao SSP-56", "regulationMark": "H"}),
  "SSP-177": () => Object.assign(new C67(), {"set": "SSP", "setNumber": "177", "fullName": "Gravity Mountain SSP-177", "regulationMark": "H"}),
  "SSP-170": () => Object.assign(new C68(), {"set": "SSP", "setNumber": "170", "fullName": "Cyrano SSP-170", "regulationMark": "H"}),
  "JTG-56": () => Object.assign(new C69(), {"set": "JTG", "setNumber": "56", "fullName": "Lillie's Clefairy ex JTG-56", "regulationMark": "I"}),
  "JTG-120": () => Object.assign(new C70(), {"set": "JTG", "setNumber": "120", "fullName": "Dunsparce JTG-120", "regulationMark": "I"}),
  "JTG-159": () => Object.assign(new C71(), {"set": "JTG", "setNumber": "159", "fullName": "Spiky Energy JTG-159", "regulationMark": "I"}),
  "TEF-25": () => Object.assign(new C72(), {"set": "TEF", "setNumber": "25", "fullName": "Iron Leaves ex TEF-25", "regulationMark": "H"}),
  "TEF-129": () => Object.assign(new C73(), {"set": "TEF", "setNumber": "129", "fullName": "Dudunsparce TEF-129", "regulationMark": "H"}),
  "TEF-145": () => Object.assign(new C74(), {"set": "TEF", "setNumber": "145", "fullName": "Ciphermaniac's Codebreaking TEF-145", "regulationMark": "H"}),
  "TEF-161": () => Object.assign(new C75(), {"set": "TEF", "setNumber": "161", "fullName": "Mist Energy TEF-161", "regulationMark": "H"}),
  "SCR-131": () => Object.assign(new C76(), {"set": "SCR", "setNumber": "131", "fullName": "Area Zero Underdepths SCR-131", "regulationMark": "H"}),
  "SCR-135": () => Object.assign(new C77(), {"set": "SCR", "setNumber": "135", "fullName": "Glass Trumpet SCR-135", "regulationMark": "H"}),
  "SFA-64": () => Object.assign(new C78(), {"set": "SFA", "setNumber": "64", "fullName": "Xerosic's Machinations SFA-64", "regulationMark": "H"}),
  "PFL-91": () => Object.assign(new C79(), {"set": "PFL", "setNumber": "91", "fullName": "Jumbo Ice Cream PFL-91", "regulationMark": "I"}),
  "CRI-82": () => Object.assign(new C80(), {"set": "CRI", "setNumber": "82", "fullName": "Special Red Card CRI-82", "regulationMark": "J"}),
  "CRI-80": () => Object.assign(new C81(), {"set": "CRI", "setNumber": "80", "fullName": "Prism Tower CRI-80", "regulationMark": "J"}),
  "DRI-173": () => Object.assign(new C82(), {"set": "DRI", "setNumber": "173", "fullName": "Team Rocket's Factory DRI-173", "regulationMark": "I"}),
  "TEF-146": () => Object.assign(new C83(), {"set": "TEF", "setNumber": "146", "fullName": "Eri TEF-146", "regulationMark": "H"}),
  "TEF-152": () => Object.assign(new C84(), {"set": "TEF", "setNumber": "152", "fullName": "Hero's Cape TEF-152", "regulationMark": "H"}),
  "WHT-84": () => Object.assign(new C85(), {"set": "WHT", "setNumber": "84", "fullName": "Hilda WHT-84", "regulationMark": "I"}),
  "POR-77": () => Object.assign(new C86(), {"set": "POR", "setNumber": "77", "fullName": "Lumiose City POR-77", "regulationMark": "J"}),
  "POR-86": () => Object.assign(new C87(), {"set": "POR", "setNumber": "86", "fullName": "Growing [G] Energy POR-86", "regulationMark": "J"}),
  "MEE-1": () => Object.assign(new C88(), {"set": "MEE", "setNumber": "1", "fullName": "Grass Energy MEE-1", "regulationMark": "ENERGY"}),
  "MEE-2": () => Object.assign(new C89(), {"set": "MEE", "setNumber": "2", "fullName": "Fire Energy MEE-2", "regulationMark": "ENERGY"}),
  "MEE-3": () => Object.assign(new C90(), {"set": "MEE", "setNumber": "3", "fullName": "Water Energy MEE-3", "regulationMark": "ENERGY"}),
  "MEE-4": () => Object.assign(new C91(), {"set": "MEE", "setNumber": "4", "fullName": "Lightning Energy MEE-4", "regulationMark": "ENERGY"}),
  "MEE-5": () => Object.assign(new C92(), {"set": "MEE", "setNumber": "5", "fullName": "Psychic Energy MEE-5", "regulationMark": "ENERGY"}),
  "MEE-6": () => Object.assign(new C93(), {"set": "MEE", "setNumber": "6", "fullName": "Fighting Energy MEE-6", "regulationMark": "ENERGY"}),
  "MEE-7": () => Object.assign(new C94(), {"set": "MEE", "setNumber": "7", "fullName": "Darkness Energy MEE-7", "regulationMark": "ENERGY"}),
  "TWM-149": () => Object.assign(new C95(), {"set": "TWM", "setNumber": "149", "fullName": "Festival Grounds TWM-149", "regulationMark": "H"}),
  "BLK-84": () => Object.assign(new C96(), {"set": "BLK", "setNumber": "84", "fullName": "Pok\u00e9gear 3.0 BLK-84", "regulationMark": "I"}),
  "MEG-123": () => Object.assign(new C97(), {"set": "MEG", "setNumber": "123", "fullName": "Pok\u00e9mon Center Lady MEG-123", "regulationMark": "I"}),
};
export const CARD_METADATA: Record<string, {cardId:string; name:string; engineName:string; regulationMark:string}> = {
  "TWM-128": {
    "cardId": "TWM-128",
    "name": "Dreepy",
    "engineName": "Dreepy TWM-128",
    "regulationMark": "H"
  },
  "TWM-129": {
    "cardId": "TWM-129",
    "name": "Drakloak",
    "engineName": "Drakloak TWM-129",
    "regulationMark": "H"
  },
  "TWM-130": {
    "cardId": "TWM-130",
    "name": "Dragapult ex",
    "engineName": "Dragapult ex TWM-130",
    "regulationMark": "H"
  },
  "TWM-25": {
    "cardId": "TWM-25",
    "name": "Teal Mask Ogerpon ex",
    "engineName": "Teal Mask Ogerpon ex TWM-25",
    "regulationMark": "H"
  },
  "TWM-95": {
    "cardId": "TWM-95",
    "name": "Munkidori",
    "engineName": "Munkidori TWM-95",
    "regulationMark": "H"
  },
  "TWM-107": {
    "cardId": "TWM-107",
    "name": "Hawlucha",
    "engineName": "Hawlucha TWM-107",
    "regulationMark": "H"
  },
  "TWM-145": {
    "cardId": "TWM-145",
    "name": "Carmine",
    "engineName": "Carmine TWM-145",
    "regulationMark": "H"
  },
  "TEF-123": {
    "cardId": "TEF-123",
    "name": "Raging Bolt ex",
    "engineName": "Raging Bolt ex TEF-123",
    "regulationMark": "H"
  },
  "TEF-144": {
    "cardId": "TEF-144",
    "name": "Buddy-Buddy Poffin",
    "engineName": "Buddy-Buddy Poffin TEF-144",
    "regulationMark": "H"
  },
  "TEF-150": {
    "cardId": "TEF-150",
    "name": "Hand Trimmer",
    "engineName": "Hand Trimmer TEF-150",
    "regulationMark": "H"
  },
  "DRI-134": {
    "cardId": "DRI-134",
    "name": "Marnie's Impidimp",
    "engineName": "Marnie's Impidimp DRI-134",
    "regulationMark": "I"
  },
  "DRI-135": {
    "cardId": "DRI-135",
    "name": "Marnie's Morgrem",
    "engineName": "Marnie's Morgrem DRI-135",
    "regulationMark": "I"
  },
  "DRI-136": {
    "cardId": "DRI-136",
    "name": "Marnie's Grimmsnarl ex",
    "engineName": "Marnie's Grimmsnarl ex DRI-136",
    "regulationMark": "I"
  },
  "DRI-11": {
    "cardId": "DRI-11",
    "name": "Dwebble",
    "engineName": "Dwebble DRI-11",
    "regulationMark": "I"
  },
  "DRI-12": {
    "cardId": "DRI-12",
    "name": "Crustle",
    "engineName": "Crustle DRI-12",
    "regulationMark": "I"
  },
  "DRI-10": {
    "cardId": "DRI-10",
    "name": "Shaymin",
    "engineName": "Shaymin DRI-10",
    "regulationMark": "I"
  },
  "SFA-61": {
    "cardId": "SFA-61",
    "name": "Night Stretcher",
    "engineName": "Night Stretcher SFA-61",
    "regulationMark": "H"
  },
  "SFA-38": {
    "cardId": "SFA-38",
    "name": "Fezandipiti ex",
    "engineName": "Fezandipiti ex SFA-38",
    "regulationMark": "H"
  },
  "SCR-133": {
    "cardId": "SCR-133",
    "name": "Crispin",
    "engineName": "Crispin SCR-133",
    "regulationMark": "H"
  },
  "SCR-137": {
    "cardId": "SCR-137",
    "name": "Gravity Gemstone",
    "engineName": "Gravity Gemstone SCR-137",
    "regulationMark": "H"
  },
  "MEG-76": {
    "cardId": "MEG-76",
    "name": "Riolu",
    "engineName": "Riolu MEG-76",
    "regulationMark": "I"
  },
  "MEG-77": {
    "cardId": "MEG-77",
    "name": "Mega Lucario ex",
    "engineName": "Mega Lucario ex MEG-77",
    "regulationMark": "I"
  },
  "MEG-119": {
    "cardId": "MEG-119",
    "name": "Lillie's Determination",
    "engineName": "Lillie's Determination MEG-119",
    "regulationMark": "I"
  },
  "MEG-116": {
    "cardId": "MEG-116",
    "name": "Fighting Gong",
    "engineName": "Fighting Gong MEG-116",
    "regulationMark": "I"
  },
  "MEG-121": {
    "cardId": "MEG-121",
    "name": "Mega Signal",
    "engineName": "Mega Signal MEG-121",
    "regulationMark": "I"
  },
  "MEG-132": {
    "cardId": "MEG-132",
    "name": "Wally's Compassion",
    "engineName": "Wally's Compassion MEG-132",
    "regulationMark": "I"
  },
  "MEG-114": {
    "cardId": "MEG-114",
    "name": "Boss's Orders",
    "engineName": "Boss's Orders MEG-114",
    "regulationMark": "I"
  },
  "MEG-125": {
    "cardId": "MEG-125",
    "name": "Rare Candy",
    "engineName": "Rare Candy MEG-125",
    "regulationMark": "I"
  },
  "MEG-130": {
    "cardId": "MEG-130",
    "name": "Switch",
    "engineName": "Switch MEG-130",
    "regulationMark": "I"
  },
  "MEG-131": {
    "cardId": "MEG-131",
    "name": "Ultra Ball",
    "engineName": "Ultra Ball MEG-131",
    "regulationMark": "I"
  },
  "MEG-115": {
    "cardId": "MEG-115",
    "name": "Energy Switch",
    "engineName": "Energy Switch MEG-115",
    "regulationMark": "I"
  },
  "SVE-1": {
    "cardId": "SVE-1",
    "name": "Grass Energy",
    "engineName": "Grass Energy SVE-1",
    "regulationMark": "ENERGY"
  },
  "SVE-2": {
    "cardId": "SVE-2",
    "name": "Fire Energy",
    "engineName": "Fire Energy SVE-2",
    "regulationMark": "ENERGY"
  },
  "SVE-4": {
    "cardId": "SVE-4",
    "name": "Lightning Energy",
    "engineName": "Lightning Energy SVE-4",
    "regulationMark": "ENERGY"
  },
  "SVE-5": {
    "cardId": "SVE-5",
    "name": "Psychic Energy",
    "engineName": "Psychic Energy SVE-5",
    "regulationMark": "ENERGY"
  },
  "SVE-6": {
    "cardId": "SVE-6",
    "name": "Fighting Energy",
    "engineName": "Fighting Energy SVE-6",
    "regulationMark": "ENERGY"
  },
  "SVE-7": {
    "cardId": "SVE-7",
    "name": "Darkness Energy",
    "engineName": "Darkness Energy SVE-7",
    "regulationMark": "ENERGY"
  },
  "POR-62": {
    "cardId": "POR-62",
    "name": "Meowth ex",
    "engineName": "Meowth ex POR-62",
    "regulationMark": "J"
  },
  "POR-84": {
    "cardId": "POR-84",
    "name": "Rosa's Encouragement",
    "engineName": "Rosa's Encouragement POR-84",
    "regulationMark": "J"
  },
  "POR-81": {
    "cardId": "POR-81",
    "name": "Pok\u00e9 Pad",
    "engineName": "Pok\u00e9 Pad POR-81",
    "regulationMark": "J"
  },
  "POR-76": {
    "cardId": "POR-76",
    "name": "Judge",
    "engineName": "Judge POR-76",
    "regulationMark": "J"
  },
  "POR-71": {
    "cardId": "POR-71",
    "name": "Crushing Hammer",
    "engineName": "Crushing Hammer POR-71",
    "regulationMark": "J"
  },
  "MEG-104": {
    "cardId": "MEG-104",
    "name": "Mega Kangaskhan ex",
    "engineName": "Mega Kangaskhan ex MEG-104",
    "regulationMark": "I"
  },
  "MEG-75": {
    "cardId": "MEG-75",
    "name": "Solrock",
    "engineName": "Solrock MEG-75",
    "regulationMark": "I"
  },
  "MEG-74": {
    "cardId": "MEG-74",
    "name": "Lunatone",
    "engineName": "Lunatone MEG-74",
    "regulationMark": "I"
  },
  "MEG-72": {
    "cardId": "MEG-72",
    "name": "Makuhita",
    "engineName": "Makuhita MEG-72",
    "regulationMark": "I"
  },
  "MEG-73": {
    "cardId": "MEG-73",
    "name": "Hariyama",
    "engineName": "Hariyama MEG-73",
    "regulationMark": "I"
  },
  "MEG-88": {
    "cardId": "MEG-88",
    "name": "Yveltal",
    "engineName": "Yveltal MEG-88",
    "regulationMark": "I"
  },
  "MEG-124": {
    "cardId": "MEG-124",
    "name": "Premium Power Pro",
    "engineName": "Premium Power Pro MEG-124",
    "regulationMark": "I"
  },
  "MEG-127": {
    "cardId": "MEG-127",
    "name": "Risky Ruins",
    "engineName": "Risky Ruins MEG-127",
    "regulationMark": "I"
  },
  "ASC-16": {
    "cardId": "ASC-16",
    "name": "Budew",
    "engineName": "Budew ASC-16",
    "regulationMark": "H"
  },
  "ASC-46": {
    "cardId": "ASC-46",
    "name": "Snorunt",
    "engineName": "Snorunt ASC-46",
    "regulationMark": "I"
  },
  "ASC-142": {
    "cardId": "ASC-142",
    "name": "Fezandipiti ex",
    "engineName": "Fezandipiti ex ASC-142",
    "regulationMark": "H"
  },
  "ASC-181": {
    "cardId": "ASC-181",
    "name": "Air Balloon",
    "engineName": "Air Balloon ASC-181",
    "regulationMark": "I"
  },
  "ASC-196": {
    "cardId": "ASC-196",
    "name": "Night Stretcher",
    "engineName": "Night Stretcher ASC-196",
    "regulationMark": "H"
  },
  "PBL-78": {
    "cardId": "PBL-78",
    "name": "Gwynn",
    "engineName": "Gwynn PBL-78",
    "regulationMark": "J"
  },
  "TWM-53": {
    "cardId": "TWM-53",
    "name": "Froslass",
    "engineName": "Froslass TWM-53",
    "regulationMark": "H"
  },
  "TWM-141": {
    "cardId": "TWM-141",
    "name": "Bloodmoon Ursaluna ex",
    "engineName": "Bloodmoon Ursaluna ex TWM-141",
    "regulationMark": "H"
  },
  "TWM-64": {
    "cardId": "TWM-64",
    "name": "Wellspring Mask Ogerpon ex",
    "engineName": "Wellspring Mask Ogerpon ex TWM-64",
    "regulationMark": "H"
  },
  "TWM-163": {
    "cardId": "TWM-163",
    "name": "Secret Box",
    "engineName": "Secret Box TWM-163",
    "regulationMark": "H"
  },
  "TWM-165": {
    "cardId": "TWM-165",
    "name": "Unfair Stamp",
    "engineName": "Unfair Stamp TWM-165",
    "regulationMark": "H"
  },
  "TWM-150": {
    "cardId": "TWM-150",
    "name": "Handheld Fan",
    "engineName": "Handheld Fan TWM-150",
    "regulationMark": "H"
  },
  "TWM-148": {
    "cardId": "TWM-148",
    "name": "Enhanced Hammer",
    "engineName": "Enhanced Hammer TWM-148",
    "regulationMark": "H"
  },
  "DRI-176": {
    "cardId": "DRI-176",
    "name": "Team Rocket's Petrel",
    "engineName": "Team Rocket's Petrel DRI-176",
    "regulationMark": "I"
  },
  "DRI-169": {
    "cardId": "DRI-169",
    "name": "Spikemuth Gym",
    "engineName": "Spikemuth Gym DRI-169",
    "regulationMark": "I"
  },
  "SSP-76": {
    "cardId": "SSP-76",
    "name": "Latias ex",
    "engineName": "Latias ex SSP-76",
    "regulationMark": "H"
  },
  "SSP-56": {
    "cardId": "SSP-56",
    "name": "Chien-Pao",
    "engineName": "Chien-Pao SSP-56",
    "regulationMark": "H"
  },
  "SSP-177": {
    "cardId": "SSP-177",
    "name": "Gravity Mountain",
    "engineName": "Gravity Mountain SSP-177",
    "regulationMark": "H"
  },
  "SSP-170": {
    "cardId": "SSP-170",
    "name": "Cyrano",
    "engineName": "Cyrano SSP-170",
    "regulationMark": "H"
  },
  "JTG-56": {
    "cardId": "JTG-56",
    "name": "Lillie's Clefairy ex",
    "engineName": "Lillie's Clefairy ex JTG-56",
    "regulationMark": "I"
  },
  "JTG-120": {
    "cardId": "JTG-120",
    "name": "Dunsparce",
    "engineName": "Dunsparce JTG-120",
    "regulationMark": "I"
  },
  "JTG-159": {
    "cardId": "JTG-159",
    "name": "Spiky Energy",
    "engineName": "Spiky Energy JTG-159",
    "regulationMark": "I"
  },
  "TEF-25": {
    "cardId": "TEF-25",
    "name": "Iron Leaves ex",
    "engineName": "Iron Leaves ex TEF-25",
    "regulationMark": "H"
  },
  "TEF-129": {
    "cardId": "TEF-129",
    "name": "Dudunsparce",
    "engineName": "Dudunsparce TEF-129",
    "regulationMark": "H"
  },
  "TEF-145": {
    "cardId": "TEF-145",
    "name": "Ciphermaniac's Codebreaking",
    "engineName": "Ciphermaniac's Codebreaking TEF-145",
    "regulationMark": "H"
  },
  "TEF-161": {
    "cardId": "TEF-161",
    "name": "Mist Energy",
    "engineName": "Mist Energy TEF-161",
    "regulationMark": "H"
  },
  "SCR-131": {
    "cardId": "SCR-131",
    "name": "Area Zero Underdepths",
    "engineName": "Area Zero Underdepths SCR-131",
    "regulationMark": "H"
  },
  "SCR-135": {
    "cardId": "SCR-135",
    "name": "Glass Trumpet",
    "engineName": "Glass Trumpet SCR-135",
    "regulationMark": "H"
  },
  "SFA-64": {
    "cardId": "SFA-64",
    "name": "Xerosic's Machinations",
    "engineName": "Xerosic's Machinations SFA-64",
    "regulationMark": "H"
  },
  "PFL-91": {
    "cardId": "PFL-91",
    "name": "Jumbo Ice Cream",
    "engineName": "Jumbo Ice Cream PFL-91",
    "regulationMark": "I"
  },
  "CRI-82": {
    "cardId": "CRI-82",
    "name": "Special Red Card",
    "engineName": "Special Red Card CRI-82",
    "regulationMark": "J"
  },
  "CRI-80": {
    "cardId": "CRI-80",
    "name": "Prism Tower",
    "engineName": "Prism Tower CRI-80",
    "regulationMark": "J"
  },
  "DRI-173": {
    "cardId": "DRI-173",
    "name": "Team Rocket's Factory",
    "engineName": "Team Rocket's Factory DRI-173",
    "regulationMark": "I"
  },
  "TEF-146": {
    "cardId": "TEF-146",
    "name": "Eri",
    "engineName": "Eri TEF-146",
    "regulationMark": "H"
  },
  "TEF-152": {
    "cardId": "TEF-152",
    "name": "Hero's Cape",
    "engineName": "Hero's Cape TEF-152",
    "regulationMark": "H"
  },
  "WHT-84": {
    "cardId": "WHT-84",
    "name": "Hilda",
    "engineName": "Hilda WHT-84",
    "regulationMark": "I"
  },
  "POR-77": {
    "cardId": "POR-77",
    "name": "Lumiose City",
    "engineName": "Lumiose City POR-77",
    "regulationMark": "J"
  },
  "POR-86": {
    "cardId": "POR-86",
    "name": "Growing [G] Energy",
    "engineName": "Growing [G] Energy POR-86",
    "regulationMark": "J"
  },
  "MEE-1": {
    "cardId": "MEE-1",
    "name": "Grass Energy",
    "engineName": "Grass Energy MEE-1",
    "regulationMark": "ENERGY"
  },
  "MEE-2": {
    "cardId": "MEE-2",
    "name": "Fire Energy",
    "engineName": "Fire Energy MEE-2",
    "regulationMark": "ENERGY"
  },
  "MEE-3": {
    "cardId": "MEE-3",
    "name": "Water Energy",
    "engineName": "Water Energy MEE-3",
    "regulationMark": "ENERGY"
  },
  "MEE-4": {
    "cardId": "MEE-4",
    "name": "Lightning Energy",
    "engineName": "Lightning Energy MEE-4",
    "regulationMark": "ENERGY"
  },
  "MEE-5": {
    "cardId": "MEE-5",
    "name": "Psychic Energy",
    "engineName": "Psychic Energy MEE-5",
    "regulationMark": "ENERGY"
  },
  "MEE-6": {
    "cardId": "MEE-6",
    "name": "Fighting Energy",
    "engineName": "Fighting Energy MEE-6",
    "regulationMark": "ENERGY"
  },
  "MEE-7": {
    "cardId": "MEE-7",
    "name": "Darkness Energy",
    "engineName": "Darkness Energy MEE-7",
    "regulationMark": "ENERGY"
  },
  "TWM-149": {
    "cardId": "TWM-149",
    "name": "Festival Grounds",
    "engineName": "Festival Grounds TWM-149",
    "regulationMark": "H"
  },
  "BLK-84": {
    "cardId": "BLK-84",
    "name": "Pok\u00e9gear 3.0",
    "engineName": "Pok\u00e9gear 3.0 BLK-84",
    "regulationMark": "I"
  },
  "MEG-123": {
    "cardId": "MEG-123",
    "name": "Pok\u00e9mon Center Lady",
    "engineName": "Pok\u00e9mon Center Lady MEG-123",
    "regulationMark": "I"
  }
};
export const manifests = [D0,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14,D15,D16,D17,D18,D19];
