"""Generate explicit executable-card and manifest imports from audited registry.
Never rewrites lists, counts, sources, hashes, or validation assertions.
"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
entries=json.loads((ROOT/'formats/card-registry.json').read_text())['cards']
imports=[];factories=[];metadata={}
for i,e in enumerate(entries):
    imports.append(f"import {{ {e['class']} as C{i} }} from '../../../vendor/twinleaf/ptcg-server/src/sets/{e['path']}';")
    overrides={'set':e['cardId'].split('-')[0],'setNumber':e['cardId'].split('-')[1],'fullName':e['engineName'],'regulationMark':e['regulationMark']}
    factories.append(f"  {json.dumps(e['cardId'])}: () => Object.assign(new C{i}(), {json.dumps(overrides)}),")
    metadata[e['cardId']]={k:e[k] for k in ['cardId','name','engineName','regulationMark']}
manifest_names=[]
for i,p in enumerate(sorted((ROOT/'decks').rglob('*.json'))):
    imports.append(f"import D{i} from '../../../{p.relative_to(ROOT).as_posix()}';");manifest_names.append(f'D{i}')
(ROOT/'packages/engine/src/generated-catalog.ts').write_text('// Generated by scripts/create-catalog.py; do not edit.\n'+ '\n'.join(imports)+"\nimport { Card } from '../../../vendor/twinleaf/ptcg-server/src/game/store/card/card';\n"+'export const CARD_FACTORIES: Record<string, () => Card> = {\n'+'\n'.join(factories)+'\n};\nexport const CARD_METADATA: Record<string, {cardId:string; name:string; engineName:string; regulationMark:string}> = '+json.dumps(metadata,indent=2)+';\nexport const manifests = ['+','.join(manifest_names)+'];\n')
print(f'Generated {len(entries)} card mappings and {len(manifest_names)} immutable manifest imports.')
